repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
